log:
  level: info
  file: server.log
db:
  driver: mysql
  # uri: "root:123456@tcp(127.0.0.1:3306)/server&charset=utf8mb4&parseTime=True&loc=Local"
  uri: "ck:123456@tcp(10.0.22.60:3306)/dolphin?&charset=utf8mb4&parseTime=True&loc=Local"
